// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq58RO5W3hOILLgwbNarHU_zZB6xjf_OA',
    appId: '1:818921277963:web:fd00a5328020c78076950e',
    messagingSenderId: '818921277963',
    projectId: 'age-and-gender-detection-d41db',
    authDomain: 'age-and-gender-detection-d41db.firebaseapp.com',
    storageBucket: 'age-and-gender-detection-d41db.firebasestorage.app',
    measurementId: 'G-HEYH93KT8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIXOFwAcsvxrMsGEK5Ec21V2-Ah5phynU',
    appId: '1:818921277963:android:2d2b90fa10fbe70176950e',
    messagingSenderId: '818921277963',
    projectId: 'age-and-gender-detection-d41db',
    storageBucket: 'age-and-gender-detection-d41db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFrZPbV3fpr8k17opjIN8KUbYMMlmG_5Y',
    appId: '1:818921277963:ios:a45c671c9092c36976950e',
    messagingSenderId: '818921277963',
    projectId: 'age-and-gender-detection-d41db',
    storageBucket: 'age-and-gender-detection-d41db.firebasestorage.app',
    iosBundleId: 'com.example.ageAndGenderDetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFrZPbV3fpr8k17opjIN8KUbYMMlmG_5Y',
    appId: '1:818921277963:ios:a45c671c9092c36976950e',
    messagingSenderId: '818921277963',
    projectId: 'age-and-gender-detection-d41db',
    storageBucket: 'age-and-gender-detection-d41db.firebasestorage.app',
    iosBundleId: 'com.example.ageAndGenderDetection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq58RO5W3hOILLgwbNarHU_zZB6xjf_OA',
    appId: '1:818921277963:web:91ab97d1d1e89f4e76950e',
    messagingSenderId: '818921277963',
    projectId: 'age-and-gender-detection-d41db',
    authDomain: 'age-and-gender-detection-d41db.firebaseapp.com',
    storageBucket: 'age-and-gender-detection-d41db.firebasestorage.app',
    measurementId: 'G-B4V55XQXRZ',
  );
}
